// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Ymk2xkbs23ubjq3nhwLM1imFonhNnG8',
    appId: '1:978333159677:web:eb948d8a36bb2f33cdee94',
    messagingSenderId: '978333159677',
    projectId: 'savingsboxtest',
    authDomain: 'savingsboxtest.firebaseapp.com',
    storageBucket: 'savingsboxtest.appspot.com',
    measurementId: 'G-NG9YF40FFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5oMDAkkTlVwu_jUwhGVipwi2vrANPC28',
    appId: '1:978333159677:android:755194c5ecb21651cdee94',
    messagingSenderId: '978333159677',
    projectId: 'savingsboxtest',
    storageBucket: 'savingsboxtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpXgS5kh62bBZyPOkNUHre0x13FZomsU',
    appId: '1:978333159677:ios:2ba9fb8fb1d69cdbcdee94',
    messagingSenderId: '978333159677',
    projectId: 'savingsboxtest',
    storageBucket: 'savingsboxtest.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpXgS5kh62bBZyPOkNUHre0x13FZomsU',
    appId: '1:978333159677:ios:2ba9fb8fb1d69cdbcdee94',
    messagingSenderId: '978333159677',
    projectId: 'savingsboxtest',
    storageBucket: 'savingsboxtest.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Ymk2xkbs23ubjq3nhwLM1imFonhNnG8',
    appId: '1:978333159677:web:860e8880bba054a9cdee94',
    messagingSenderId: '978333159677',
    projectId: 'savingsboxtest',
    authDomain: 'savingsboxtest.firebaseapp.com',
    storageBucket: 'savingsboxtest.appspot.com',
    measurementId: 'G-30HS78Z09Q',
  );
}
